# Generated by Django 5.2.5 on 2025-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='mock_tests', to='tests.question'),
        ),
    ]
