# Generated by Django 5.2.5 on 2025-09-14 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_mocktest_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='negative_marks_per_question',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=5),
        ),
    ]
