# Generated by Django 5.2.5 on 2025-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_mocktest_negative_marks_per_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='total',
            new_name='total_marks',
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_unanswered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
