# Generated by Django 5.2.5 on 2025-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_contactmessage_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
